[project]
name = "torch-transformer-poet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "indralib",
    "ipywidgets",
    "jupyterlab",
    "ml-indie-tools",
    "numpy",
    "sentencepiece>=0.2.0",
    "torch",
]
